-- 01_build_core.sql
-- EXTENSIONS
CREATE EXTENSION IF NOT EXISTS postgis;

-- 1. WELL MASTER (Surface)
CREATE TABLE well_master (
    well_id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    uwi                 VARCHAR(50) UNIQUE NOT NULL, 
    well_name           VARCHAR(255),
    operator            VARCHAR(255),
    spud_date           DATE,
    surface_geom        GEOMETRY(POINT, 4269), -- NAD83 Lat/Lon
    elevation_kb        REAL, 
    attributes          JSONB DEFAULT '{}',
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 2. WELLBORE MASTER (The Hole)
CREATE TABLE wellbore_master (
    wellbore_id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    well_id             UUID REFERENCES well_master(well_id) ON DELETE CASCADE,
    wellbore_name       VARCHAR(50) DEFAULT 'OH', 
    
    -- Depths
    total_depth_md      REAL,
    total_depth_tvd     REAL,
    
    -- Trajectory Geometry (Calculated)
    trajectory_geom     GEOMETRY(LINESTRINGZ, 4269),
    
    -- Trajectory Metadata (The Fix for Grid Convergence)
    crs_epsg            INTEGER,      -- e.g. 26914 (UTM Zone 14N)
    grid_convergence    REAL,         -- Angle (True - Grid)
    calculated_at       TIMESTAMP,

    attributes          JSONB DEFAULT '{}',
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT uq_well_bore UNIQUE(well_id, wellbore_name)
);

-- 3. DIRECTIONAL SURVEYS (Raw Data)
CREATE TABLE directional_surveys (
    survey_id           UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wellbore_id         UUID REFERENCES wellbore_master(wellbore_id) ON DELETE CASCADE,
    
    survey_date         DATE,
    survey_type         VARCHAR(50), 
    is_active           BOOLEAN DEFAULT TRUE,
    
    -- The Fix for North Reference
    azimuth_ref         VARCHAR(20) DEFAULT 'True North', -- 'Grid North', 'True North'
    north_ref_offset    REAL DEFAULT 0.0,
    
    -- Data Storage (JSON Array of {md, inc, azi})
    survey_points       JSONB NOT NULL, 
    
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. TOPS (Geology)
CREATE TABLE strat_unit_dictionary (
    strat_unit_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_name           VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE formation_tops (
    top_id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wellbore_id         UUID REFERENCES wellbore_master(wellbore_id) ON DELETE CASCADE,
    strat_unit_id       INTEGER REFERENCES strat_unit_dictionary(strat_unit_id),
    
    depth_md            REAL NOT NULL,
    depth_tvd           REAL,
    depth_tvd_ss        REAL,
    
    interpreter         VARCHAR(100),
    pick_quality        VARCHAR(50),
    
    -- The Fix for Faults
    occurrence          INTEGER DEFAULT 1, 
    feature_context     VARCHAR(100), 
    
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    -- Allow same formation twice ONLY if occurrence is different
    CONSTRAINT uq_well_strat_occurrence UNIQUE (wellbore_id, strat_unit_id, interpreter, occurrence)
);

-- 5. CURVE CATALOG
CREATE TABLE curve_catalog (
    curve_set_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wellbore_id         UUID REFERENCES wellbore_master(wellbore_id),
    dataset_name        VARCHAR(100),
    channels            TEXT[], 
    min_depth           REAL, 
    max_depth           REAL, 
    file_path           TEXT NOT NULL, 
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- INDEXES
CREATE INDEX idx_well_uwi ON well_master(uwi);
CREATE INDEX idx_well_geom ON well_master USING GIST (surface_geom);
CREATE INDEX idx_tops_strat ON formation_tops(strat_unit_id);