-- ======================================================================
-- SCRIPT: 03_build_geology.sql
-- PURPOSE: Subsurface geology, logs, and catalogs.
-- DEPENDENCIES: 01_build_core.sql
-- ======================================================================

-- 1. STRATIGRAPHY DICTIONARY
-- Normalizes formation names to prevent "Eagle Ford" vs "Eagleford"
CREATE TABLE strat_unit_dictionary (
    strat_unit_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_name           VARCHAR(100) UNIQUE NOT NULL
);

-- 2. FORMATION TOPS
CREATE TABLE formation_tops (
    top_id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wellbore_id         UUID REFERENCES wellbore_master(wellbore_id) ON DELETE CASCADE,
    strat_unit_id       INTEGER REFERENCES strat_unit_dictionary(strat_unit_id),
    
    depth_md            REAL NOT NULL,
    depth_tvd           REAL, -- Warning: Needs update if Survey changes
    
    interpreter         VARCHAR(100),
    pick_quality        VARCHAR(50),
    
    occurrence          INTEGER DEFAULT 1, -- Handles faults/repeated sections
    feature_context     VARCHAR(100), -- 'Fault Cut', 'Erosion'
    
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT uq_well_strat_occurrence UNIQUE (wellbore_id, strat_unit_id, interpreter, occurrence)
);

-- 3. ROCK SAMPLES (Core & Cuttings Inventory)
CREATE TABLE rock_samples (
   sample_id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wellbore_id         UUID REFERENCES wellbore_master(wellbore_id) ON DELETE CASCADE,
    sample_type         VARCHAR(50), -- 'Conventional Core', 'Sidewall', 'Cuttings'
    sample_name         VARCHAR(100),
    top_depth_md        REAL, 
    base_depth_md       REAL, 
    storage_location    VARCHAR(255),
    attributes          JSONB DEFAULT '{}',
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 4. CURVE CATALOG (Logs)
-- Metadata pointing to LAS/Parquet files in the lake
CREATE TABLE curve_catalog (
    curve_set_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wellbore_id         UUID REFERENCES wellbore_master(wellbore_id),
    dataset_name        VARCHAR(100),
    channels            TEXT[], -- Array of curve names ['GR', 'RES']
    min_depth           REAL, 
    max_depth           REAL, 
    file_path           TEXT NOT NULL, 
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. MEDIA CATALOG
-- Metadata pointing to Photos/Reports in the lake
CREATE TABLE media_catalog (
    media_id            UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wellbore_id         UUID REFERENCES wellbore_master(wellbore_id),
    media_type          VARCHAR(50), 
    file_format         VARCHAR(20), 
    file_path           TEXT NOT NULL, 
    top_depth_md        REAL, 
    base_depth_md       REAL, 
    description         TEXT,
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. INDEXES
CREATE INDEX idx_tops_strat ON formation_tops(strat_unit_id);
CREATE INDEX idx_tops_wb ON formation_tops(wellbore_id);