-- 1. SETUP EXTENSIONS
-- PostGIS is required for spatial data.
CREATE EXTENSION IF NOT EXISTS postgis;

-- 2. WELL MASTER (Surface/Header)
CREATE TABLE well_master (
    well_id             UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    uwi                 VARCHAR(50) UNIQUE NOT NULL, 
    well_name           VARCHAR(255),
    operator            VARCHAR(255),
    spud_date           DATE,
    
    -- GEOMETRY (NAD83)
    surface_geom        GEOMETRY(POINT, 4269), --'CRS: NAD83 (EPSG:4269).'
    
    attributes          JSONB DEFAULT '{}',
    
    -- Audit Columns (Fix 2)
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 3. WELLBORE MASTER (The Hole)
CREATE TABLE wellbore_master (
    wellbore_id         UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    well_id             UUID REFERENCES well_master(well_id) ON DELETE CASCADE,
    wellbore_name       VARCHAR(50) DEFAULT 'OH', 
    
    -- Depths
    total_depth_md      REAL, -- 'UNIT: Feet (Imperial).'
    total_depth_tvd     REAL, -- 'UNIT: Feet (Imperial).'
    
    -- Trajectory (3D Path)
    trajectory_geom     GEOMETRY(LINESTRINGZ, 4269),
    
    attributes          JSONB DEFAULT '{}',
    
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    
    CONSTRAINT uq_well_bore UNIQUE(well_id, wellbore_name)
);

-- 4. TOPS DICTIONARY & TABLE
CREATE TABLE strat_unit_dictionary (
    strat_unit_id       INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_name           VARCHAR(100) UNIQUE NOT NULL
);

CREATE TABLE formation_tops (
    CREATE TABLE formation_tops (
    top_id              UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wellbore_id         UUID REFERENCES wellbore_master(wellbore_id) ON DELETE CASCADE,
    strat_unit_id       INTEGER REFERENCES strat_unit_dictionary(strat_unit_id),
    
    depth_md            REAL NOT NULL, --'UNIT: Feet (Imperial).'
    interpreter         VARCHAR(100),
    pick_quality        VARCHAR(50),
    
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 5. CURVE CATALOG (The Lakehouse Index)
CREATE TABLE curve_catalog (
    curve_set_id        UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    wellbore_id         UUID REFERENCES wellbore_master(wellbore_id),
    
    dataset_name        VARCHAR(100),
    channels            TEXT[], 
    
    min_depth           REAL, -- 'UNIT: Feet (Imperial).'
    max_depth           REAL, -- 'UNIT: Feet (Imperial).'
    
    file_path           TEXT NOT NULL, -- S3 or File Path
    created_at          TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

-- 6. INDEXING
CREATE INDEX idx_well_uwi ON well_master(uwi);
CREATE INDEX idx_well_geom ON well_master USING GIST (surface_geom);
CREATE INDEX idx_media_type ON media_catalog(media_type);
CREATE INDEX idx_curve_channels ON curve_catalog USING GIN (channels);